[model]
seed = 111
batch_size = 64
seq_size = 20
init_size = 5

state_size = 8
belief_size = 128
num_layers = 3

obs_std = 1.0
obs_bit = 5

learn_rate = 0.0005
grad_clip = 10.0
max_iters = 500000

seg_num = 5
seg_len = 8

max_beta = 1.0
min_beta = 0.1
beta_anneal = 100

log_dir = './asset/log/'