# coding: UTF-8
[model]
seed = 115 # 乱数のシード
batch_size = 64 #batch_size
seq_size = 20 # 観測系列の長さ
init_size = 5 #　観測系列に加える長さ

state_size = 8 # 状態の次元
belief_size = 128 #　h, cの次元
num_layers = 3 # 層の数

obs_std = 1.0
obs_bit = 5

learn_rate = 0.0005
grad_clip = 10.0
max_iters = 100

seg_num = 3
seg_len = 8

max_beta = 1.0
min_beta = 0.1
beta_anneal = 100

test_times = 10 # 何回毎にテストするか
log_dir = './asset/log/' # ログ出力先
gpu_ids = [3, 4] #使用するgpuのid
data_path = '/export/space/n1610492/imgs_10k_variable.npy' # データセットpath
data_length = 10000 # データの長さ
fix = false

[dataset]
target_label = [0, 1, 3, 5, 7] # 使用する数字
data_length = 1000000 # で＝たセットの長さ
min_len = 3 # 最小の長さ
max_len = 8 # 最大の長さ
fix = false #　数字の画像を固定するか
save_name = '/export/space/n1610492/imgs_10k_variable'　#データセットのファイル名